// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXIuC1bJb0Ukoi0Atf9Pwku96X9ZMiBM4',
    appId: '1:740178959092:android:538d9340c53aa56d36dca1',
    messagingSenderId: '740178959092',
    projectId: 'chatus-9afe0',
    storageBucket: 'chatus-9afe0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdWK6hbm0k-QPmdS63pBoJlbYYkNq_V2c',
    appId: '1:740178959092:ios:e6aefa6e01801b0536dca1',
    messagingSenderId: '740178959092',
    projectId: 'chatus-9afe0',
    storageBucket: 'chatus-9afe0.appspot.com',
    androidClientId: '740178959092-6r463gll051eenne15uvijjousgffet8.apps.googleusercontent.com',
    iosClientId: '740178959092-ktcmjvuqddtslbgi0mrs10ct111nqo9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );
}
